corrected path to match faceswaplab_globals.py edit
This path change fixes the following error (tested on my own setup  (installed via Stability Matrix on win11) ; 

StabilityMatrix-win-x64\\Data\\Packages\\Stable Diffusion WebUI Forge\\extensions\\sd-webui-faceswaplab\\references\\woman.png'
Traceback (most recent call last):
  File "D:\AI\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\extensions\sd-webui-forge-faceswaplab\scripts\faceswaplab_swapping\face_checkpoints.py", line 76, in build_face_checkpoint_and_save
    reference_preview_img = Image.open(
  File "D:\AI\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\PIL\Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\StabilityMatrix-win-x64\\Data\\Packages\\Stable Diffusion WebUI Forge\\extensions\\sd-webui-faceswaplab\\references\\woman.png'

D:\AI\StabilityMatrix-win-x64\Data\Packages\Stable Diffusion WebUI Forge\venv\lib\site-packages\insightface\utils\transform.py:68: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  P = np.linalg.lstsq(X_homo, Y)[0].T # Affine matrix. 3 x 4